version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: twodu
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/usr/app/src/
    container_name: server
    depends_on:
      - db
    ports:
      - "3001:3001"
    command: npm run dev
     